name: Build and Release Go EXEs

on:
  push:
    tags:
      - 'v*'          # runs when you push a tag like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build registry
        run: go build -o registry.exe ./Registry/

      - name: Build emberdb
        run: go build -o emberdb.exe ./cmd/emberdb/

      - name: Build client
        run: go build -o client.exe client.go

      - name: Prepare release folder
        run: |
          mkdir release
          mv registry.exe emberdb.exe client.exe release/
          cp README.md release/

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
